# Generated by Django 3.1.7 on 2021-04-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
    ]
